# Generated by Django 3.1.2 on 2020-10-05 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_completebloodcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completebloodcount',
            options={'verbose_name': 'Общий анализ крови', 'verbose_name_plural': 'Общий анализ крови'},
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.patients'),
            preserve_default=False,
        ),
    ]
