# Generated by Django 3.1.2 on 2020-10-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201005_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completebloodcount',
            name='date_cbc',
            field=models.DateField(null=True, verbose_name='Дата анализа'),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='hb_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Гемоглобин'),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='rbc_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Эритроциты'),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='wbc_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Лейкоциты'),
        ),
    ]
