# Generated by Django 3.1.2 on 2020-10-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201005_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='completebloodcount',
            name='bas_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Базофилы, %'),
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='eos_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Эозинофилы, %'),
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='esr_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Скорость оседания эритроцитов, мм/ч'),
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='lym_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Лимфоциты, %'),
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='mchc_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Цветовой показатель, %'),
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='mon_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Моноциты, %'),
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='rpr_cbc',
            field=models.CharField(max_length=50, null=True, verbose_name='Микрореакция'),
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='segm_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Сегментоядерные, %'),
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='stab_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Палочкоядерные, %'),
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='young_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Юные нейтрофилы, %'),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='hb_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Гемоглобин, г/л'),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='rbc_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Эритроциты, 10^12/л'),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='wbc_cbc',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Лейкоциты, 10^9/л'),
        ),
    ]
