# Generated by Django 3.1.2 on 2020-10-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201005_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completebloodcount',
            options={'verbose_name': 'Общий анализ крови', 'verbose_name_plural': 'Общие анализы крови'},
        ),
        migrations.CreateModel(
            name='SputumTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stt', models.DateField(null=True, verbose_name='Дата анализа')),
                ('color_stt', models.CharField(max_length=50, null=True, verbose_name='Цвет')),
                ('nature_stt', models.CharField(max_length=50, null=True, verbose_name='Характер')),
                ('consistency_stt', models.CharField(max_length=50, null=True, verbose_name='Консистенция')),
                ('wbc_stt', models.CharField(max_length=50, null=True, verbose_name='Лейкоциты')),
                ('rbc_stt', models.CharField(max_length=50, null=True, verbose_name='Эритроциты')),
                ('epith_stt', models.CharField(max_length=50, null=True, verbose_name='Эпителий')),
                ('alveolar_stt', models.CharField(max_length=50, null=True, verbose_name='Альв.макрофаги')),
                ('bact_stt', models.CharField(max_length=50, null=True, verbose_name='Бактерии')),
                ('bact_tub_stt', models.CharField(max_length=50, null=True, verbose_name='Бакт.туберкулез')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patients')),
            ],
            options={
                'verbose_name': 'Общий анализ мокроты',
                'verbose_name_plural': 'Общие анализы мокроты',
            },
        ),
        migrations.CreateModel(
            name='CoagulogramTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cgt', models.DateField(null=True, verbose_name='Дата анализа')),
                ('apt_time_cgt', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='АЧТВ')),
                ('ina_cgt', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='МНО')),
                ('prot_index_cgt', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='ПТИ')),
                ('fibrin_cgt', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Фибрин')),
                ('not_data_cgt', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Пустая колонка')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patients')),
            ],
            options={
                'verbose_name': 'Коагулограмма',
                'verbose_name_plural': 'Коагулограммы',
            },
        ),
        migrations.CreateModel(
            name='ClinicalUrineTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cut', models.DateField(null=True, verbose_name='Дата анализа')),
                ('col_cut', models.CharField(max_length=50, null=True, verbose_name='Цвет')),
                ('ph_cut', models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='Кислотность')),
                ('sg_cut', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Удельный вес')),
                ('transp_cut', models.CharField(max_length=50, null=True, verbose_name='Прозрачность')),
                ('pro_cut', models.CharField(max_length=50, null=True, verbose_name='Белок')),
                ('epith_cut', models.CharField(max_length=50, null=True, verbose_name='Эпителий')),
                ('wbc_cut', models.CharField(max_length=50, null=True, verbose_name='Лейкоциты')),
                ('rbc_cut', models.CharField(max_length=50, null=True, verbose_name='Эритроциты')),
                ('salt_cut', models.CharField(max_length=50, null=True, verbose_name='Соли')),
                ('bact_cut', models.CharField(max_length=50, null=True, verbose_name='Бактерии')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patients')),
            ],
            options={
                'verbose_name': 'Общий анализ мочи',
                'verbose_name_plural': 'Общие анализы мочи',
            },
        ),
        migrations.CreateModel(
            name='BiochemicalBloodAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bba', models.DateField(null=True, verbose_name='Дата анализа')),
                ('total_pro_bba', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Общий белок')),
                ('creatin_bba', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Креатинин')),
                ('urea_bba', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Мочевина')),
                ('total_bil_bba', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Общий билирубин')),
                ('cholest_bba', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Холестирин')),
                ('alt_bba', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Аланинаминотрансфераза')),
                ('ast_bba', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Аспартатаминотрансфераза')),
                ('crp_bba', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='С-реактивный протеин')),
                ('potassium_bba', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Калий')),
                ('natr_bba', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Натрий')),
                ('not_data_bba', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Пустая колонка')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patients')),
            ],
            options={
                'verbose_name': 'Биохимический анализ крови',
                'verbose_name_plural': 'Биохимические анализы крови',
            },
        ),
    ]
