# Generated by Django 3.1.2 on 2020-10-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_patients_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
